power <- read.csv("household_power_consumption.txt", header = TRUE, sep=";", na.strings = "?")
power <- subset(power, subset = power$Date=="1/2/2007" | power$Date=="2/2/2007" | power$Date=="Date")
power$Date = as.Date(power$Date, "%d/%m/%Y")
power$Time <- paste(power$Date, power$Time, sep=" ")
power$Time <- strptime(power$Time, "%Y-%m-%d %H:%M:%S")
png(file = "plot1.png", width=480, height=480)
hist(power$Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()