power <- read.csv("household_power_consumption.txt", header = TRUE, sep=";", na.strings = "?")
power <- subset(power, subset = power$Date=="1/2/2007" | power$Date=="2/2/2007" | power$Date=="Date")
power$Date = as.Date(power$Date, "%d/%m/%Y")
power$Time <- paste(power$Date, power$Time, sep=" ")
power$Time <- strptime(power$Time, "%Y-%m-%d %H:%M:%S")
png(file = "plot4.png", width=480, height=480)
par(mfcol = c(2, 2), mar = c(4, 4, 2, 1), oma = c(1, 1, 2, 1))
plot(power$Time, type="l", power$Global_active_power, ylab="Global Active Power", xlab="")
plot(power$Time, power$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(power$Time, power$Sub_metering_2,col="red")
lines(power$Time, power$Sub_metering_3,col="blue")
legend("topright", bty = "n", lty=c(1,1), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(power$Time, type="l", power$Voltage, ylab="Voltage", xlab="datetime")
plot(power$Time, type="l", power$Global_reactive_power, ylab="Global_reactive_power", xlab="datetime")
dev.off()